//! PyO3 hashmaps over the Cartesian product of common scalar dtypes.
//!
//! 9 key dtypes (`bool`, `i8`, `i16`, `i32`, `i64`, `u8`, `u16`, `u32`,
//! `u64`) × 11 value dtypes (the same 9 plus `f32` + `f64`) = 99 PyO3
//! classes, all generated by `hashmap_macro::define_hashmap!` (see
//! `hashmap_macro.rs`). Class names follow the pattern
//! `HashMap<K><V>` with each component spelled in PascalCase
//! (`HashMapU32U16`, `HashMapI64F64`, `HashMapBoolBool`, …).
//!
//! ## Surface
//!
//! Every class exposes the same API (documented on the macro):
//!
//! - `__new__(capacity: int = 0)` — preallocate buckets when
//!   `capacity > 0`; zero-arg form preserved for back-compat.
//! - `get(key) / lookup(key) -> Optional[V]`
//! - `set(key, v) / insert(key, v)`
//! - `lookup_ndarray(keys)` — vectorized lookup; misses become the
//!   per-dtype sentinel (table below).
//! - `insert_ndarray(keys, values)` — batch insert, last-wins on dup
//!   keys.
//! - `clean()` — clear entries, retain capacity (`HashMap::clear`).
//! - `__len__()`, `__contains__(key)`.
//!
//! ## Miss sentinel per value dtype
//!
//! | Value dtype     | Sentinel                                |
//! |-----------------|-----------------------------------------|
//! | `bool`          | `false`                                 |
//! | `i8`/`i16`/`i32`/`i64` | `<dtype>::MIN`                   |
//! | `u8`/`u16`/`u32`/`u64` | `<dtype>::MAX` (all-ones)        |
//! | `f32`/`f64`     | quiet NaN (`f32::NAN` / `f64::NAN`)     |
//!
//! Callers should check membership with `__contains__` / `lookup` when
//! the sentinel value is itself a legitimate entry value.

mod adjacency_expand;
mod carrier_signs;
mod family_band_reduction;
mod flat_segments;
mod hashmap_macro;
mod identity_gather;
mod inline_bytes;
mod inline_state_fields;
mod node_ct_csr;
mod number_idx_2d;
mod once_only_inclusion;
mod promote_batched;
mod remap_walk;
mod row_inclusions;
mod segment_distinct;
mod strip_shift_prepend;
mod token_scatter;

use adjacency_expand::LiveAdjacencyKernel;
use once_only_inclusion::OnceOnlyInclusionKernel;
use carrier_signs::build_carrier_signs_kernel;
use family_band_reduction::build_family_band_reduction_kernel;
use flat_segments::build_flat_segments_kernel;
use hashmap_macro::define_hashmap;
use identity_gather::build_identity_carriers_kernel;
use inline_bytes::build_inline_bytes_kernel;
use inline_state_fields::build_inline_state_fields_kernel;
use node_ct_csr::build_node_ct_csr_kernel;
use number_idx_2d::build_number_idx_2d_kernel;
use promote_batched::build_promote_batched_kernel;
use pyo3::prelude::*;
use remap_walk::apply_remap_walk;
use row_inclusions::compute_row_inclusions_kernel;
use segment_distinct::segment_distinct_count;
use strip_shift_prepend::build_strip_shift_prepend_kernel;
use token_scatter::build_token_scatter_kernel;

// -- Generated classes -----------------------------------------------------
//
// The pattern for each invocation is:
//
//     define_hashmap!(HashMap<K><V>, <key Rust ty>, <value Rust ty>,
//                     <miss-sentinel expr>);
//
// 99 invocations follow, grouped by key type.

// ---- key: bool ----
define_hashmap!(HashMapBoolBool, bool, bool, false);
define_hashmap!(HashMapBoolI8, bool, i8, i8::MIN);
define_hashmap!(HashMapBoolI16, bool, i16, i16::MIN);
define_hashmap!(HashMapBoolI32, bool, i32, i32::MIN);
define_hashmap!(HashMapBoolI64, bool, i64, i64::MIN);
define_hashmap!(HashMapBoolU8, bool, u8, u8::MAX);
define_hashmap!(HashMapBoolU16, bool, u16, u16::MAX);
define_hashmap!(HashMapBoolU32, bool, u32, u32::MAX);
define_hashmap!(HashMapBoolU64, bool, u64, u64::MAX);
define_hashmap!(HashMapBoolF32, bool, f32, f32::NAN);
define_hashmap!(HashMapBoolF64, bool, f64, f64::NAN);

// ---- key: i8 ----
define_hashmap!(HashMapI8Bool, i8, bool, false);
define_hashmap!(HashMapI8I8, i8, i8, i8::MIN);
define_hashmap!(HashMapI8I16, i8, i16, i16::MIN);
define_hashmap!(HashMapI8I32, i8, i32, i32::MIN);
define_hashmap!(HashMapI8I64, i8, i64, i64::MIN);
define_hashmap!(HashMapI8U8, i8, u8, u8::MAX);
define_hashmap!(HashMapI8U16, i8, u16, u16::MAX);
define_hashmap!(HashMapI8U32, i8, u32, u32::MAX);
define_hashmap!(HashMapI8U64, i8, u64, u64::MAX);
define_hashmap!(HashMapI8F32, i8, f32, f32::NAN);
define_hashmap!(HashMapI8F64, i8, f64, f64::NAN);

// ---- key: i16 ----
define_hashmap!(HashMapI16Bool, i16, bool, false);
define_hashmap!(HashMapI16I8, i16, i8, i8::MIN);
define_hashmap!(HashMapI16I16, i16, i16, i16::MIN);
define_hashmap!(HashMapI16I32, i16, i32, i32::MIN);
define_hashmap!(HashMapI16I64, i16, i64, i64::MIN);
define_hashmap!(HashMapI16U8, i16, u8, u8::MAX);
define_hashmap!(HashMapI16U16, i16, u16, u16::MAX);
define_hashmap!(HashMapI16U32, i16, u32, u32::MAX);
define_hashmap!(HashMapI16U64, i16, u64, u64::MAX);
define_hashmap!(HashMapI16F32, i16, f32, f32::NAN);
define_hashmap!(HashMapI16F64, i16, f64, f64::NAN);

// ---- key: i32 ----
define_hashmap!(HashMapI32Bool, i32, bool, false);
define_hashmap!(HashMapI32I8, i32, i8, i8::MIN);
define_hashmap!(HashMapI32I16, i32, i16, i16::MIN);
define_hashmap!(HashMapI32I32, i32, i32, i32::MIN);
define_hashmap!(HashMapI32I64, i32, i64, i64::MIN);
define_hashmap!(HashMapI32U8, i32, u8, u8::MAX);
define_hashmap!(HashMapI32U16, i32, u16, u16::MAX);
define_hashmap!(HashMapI32U32, i32, u32, u32::MAX);
define_hashmap!(HashMapI32U64, i32, u64, u64::MAX);
define_hashmap!(HashMapI32F32, i32, f32, f32::NAN);
define_hashmap!(HashMapI32F64, i32, f64, f64::NAN);

// ---- key: i64 ----
define_hashmap!(HashMapI64Bool, i64, bool, false);
define_hashmap!(HashMapI64I8, i64, i8, i8::MIN);
define_hashmap!(HashMapI64I16, i64, i16, i16::MIN);
define_hashmap!(HashMapI64I32, i64, i32, i32::MIN);
define_hashmap!(HashMapI64I64, i64, i64, i64::MIN);
define_hashmap!(HashMapI64U8, i64, u8, u8::MAX);
define_hashmap!(HashMapI64U16, i64, u16, u16::MAX);
define_hashmap!(HashMapI64U32, i64, u32, u32::MAX);
define_hashmap!(HashMapI64U64, i64, u64, u64::MAX);
define_hashmap!(HashMapI64F32, i64, f32, f32::NAN);
define_hashmap!(HashMapI64F64, i64, f64, f64::NAN);

// ---- key: u8 ----
define_hashmap!(HashMapU8Bool, u8, bool, false);
define_hashmap!(HashMapU8I8, u8, i8, i8::MIN);
define_hashmap!(HashMapU8I16, u8, i16, i16::MIN);
define_hashmap!(HashMapU8I32, u8, i32, i32::MIN);
define_hashmap!(HashMapU8I64, u8, i64, i64::MIN);
define_hashmap!(HashMapU8U8, u8, u8, u8::MAX);
define_hashmap!(HashMapU8U16, u8, u16, u16::MAX);
define_hashmap!(HashMapU8U32, u8, u32, u32::MAX);
define_hashmap!(HashMapU8U64, u8, u64, u64::MAX);
define_hashmap!(HashMapU8F32, u8, f32, f32::NAN);
define_hashmap!(HashMapU8F64, u8, f64, f64::NAN);

// ---- key: u16 ----
define_hashmap!(HashMapU16Bool, u16, bool, false);
define_hashmap!(HashMapU16I8, u16, i8, i8::MIN);
define_hashmap!(HashMapU16I16, u16, i16, i16::MIN);
define_hashmap!(HashMapU16I32, u16, i32, i32::MIN);
define_hashmap!(HashMapU16I64, u16, i64, i64::MIN);
define_hashmap!(HashMapU16U8, u16, u8, u8::MAX);
define_hashmap!(HashMapU16U16, u16, u16, u16::MAX);
define_hashmap!(HashMapU16U32, u16, u32, u32::MAX);
define_hashmap!(HashMapU16U64, u16, u64, u64::MAX);
define_hashmap!(HashMapU16F32, u16, f32, f32::NAN);
define_hashmap!(HashMapU16F64, u16, f64, f64::NAN);

// ---- key: u32 ----
define_hashmap!(HashMapU32Bool, u32, bool, false);
define_hashmap!(HashMapU32I8, u32, i8, i8::MIN);
define_hashmap!(HashMapU32I16, u32, i16, i16::MIN);
define_hashmap!(HashMapU32I32, u32, i32, i32::MIN);
define_hashmap!(HashMapU32I64, u32, i64, i64::MIN);
define_hashmap!(HashMapU32U8, u32, u8, u8::MAX);
define_hashmap!(HashMapU32U16, u32, u16, u16::MAX);
define_hashmap!(HashMapU32U32, u32, u32, u32::MAX);
define_hashmap!(HashMapU32U64, u32, u64, u64::MAX);
define_hashmap!(HashMapU32F32, u32, f32, f32::NAN);
define_hashmap!(HashMapU32F64, u32, f64, f64::NAN);

// ---- key: u64 ----
define_hashmap!(HashMapU64Bool, u64, bool, false);
define_hashmap!(HashMapU64I8, u64, i8, i8::MIN);
define_hashmap!(HashMapU64I16, u64, i16, i16::MIN);
define_hashmap!(HashMapU64I32, u64, i32, i32::MIN);
define_hashmap!(HashMapU64I64, u64, i64, i64::MIN);
define_hashmap!(HashMapU64U8, u64, u8, u8::MAX);
define_hashmap!(HashMapU64U16, u64, u16, u16::MAX);
define_hashmap!(HashMapU64U32, u64, u32, u32::MAX);
define_hashmap!(HashMapU64U64, u64, u64, u64::MAX);
define_hashmap!(HashMapU64F32, u64, f32, f32::NAN);
define_hashmap!(HashMapU64F64, u64, f64, f64::NAN);

#[pymodule]
fn _native(m: &Bound<'_, PyModule>) -> PyResult<()> {
    // bool key
    m.add_class::<HashMapBoolBool>()?;
    m.add_class::<HashMapBoolI8>()?;
    m.add_class::<HashMapBoolI16>()?;
    m.add_class::<HashMapBoolI32>()?;
    m.add_class::<HashMapBoolI64>()?;
    m.add_class::<HashMapBoolU8>()?;
    m.add_class::<HashMapBoolU16>()?;
    m.add_class::<HashMapBoolU32>()?;
    m.add_class::<HashMapBoolU64>()?;
    m.add_class::<HashMapBoolF32>()?;
    m.add_class::<HashMapBoolF64>()?;

    // i8 key
    m.add_class::<HashMapI8Bool>()?;
    m.add_class::<HashMapI8I8>()?;
    m.add_class::<HashMapI8I16>()?;
    m.add_class::<HashMapI8I32>()?;
    m.add_class::<HashMapI8I64>()?;
    m.add_class::<HashMapI8U8>()?;
    m.add_class::<HashMapI8U16>()?;
    m.add_class::<HashMapI8U32>()?;
    m.add_class::<HashMapI8U64>()?;
    m.add_class::<HashMapI8F32>()?;
    m.add_class::<HashMapI8F64>()?;

    // i16 key
    m.add_class::<HashMapI16Bool>()?;
    m.add_class::<HashMapI16I8>()?;
    m.add_class::<HashMapI16I16>()?;
    m.add_class::<HashMapI16I32>()?;
    m.add_class::<HashMapI16I64>()?;
    m.add_class::<HashMapI16U8>()?;
    m.add_class::<HashMapI16U16>()?;
    m.add_class::<HashMapI16U32>()?;
    m.add_class::<HashMapI16U64>()?;
    m.add_class::<HashMapI16F32>()?;
    m.add_class::<HashMapI16F64>()?;

    // i32 key
    m.add_class::<HashMapI32Bool>()?;
    m.add_class::<HashMapI32I8>()?;
    m.add_class::<HashMapI32I16>()?;
    m.add_class::<HashMapI32I32>()?;
    m.add_class::<HashMapI32I64>()?;
    m.add_class::<HashMapI32U8>()?;
    m.add_class::<HashMapI32U16>()?;
    m.add_class::<HashMapI32U32>()?;
    m.add_class::<HashMapI32U64>()?;
    m.add_class::<HashMapI32F32>()?;
    m.add_class::<HashMapI32F64>()?;

    // i64 key
    m.add_class::<HashMapI64Bool>()?;
    m.add_class::<HashMapI64I8>()?;
    m.add_class::<HashMapI64I16>()?;
    m.add_class::<HashMapI64I32>()?;
    m.add_class::<HashMapI64I64>()?;
    m.add_class::<HashMapI64U8>()?;
    m.add_class::<HashMapI64U16>()?;
    m.add_class::<HashMapI64U32>()?;
    m.add_class::<HashMapI64U64>()?;
    m.add_class::<HashMapI64F32>()?;
    m.add_class::<HashMapI64F64>()?;

    // u8 key
    m.add_class::<HashMapU8Bool>()?;
    m.add_class::<HashMapU8I8>()?;
    m.add_class::<HashMapU8I16>()?;
    m.add_class::<HashMapU8I32>()?;
    m.add_class::<HashMapU8I64>()?;
    m.add_class::<HashMapU8U8>()?;
    m.add_class::<HashMapU8U16>()?;
    m.add_class::<HashMapU8U32>()?;
    m.add_class::<HashMapU8U64>()?;
    m.add_class::<HashMapU8F32>()?;
    m.add_class::<HashMapU8F64>()?;

    // u16 key
    m.add_class::<HashMapU16Bool>()?;
    m.add_class::<HashMapU16I8>()?;
    m.add_class::<HashMapU16I16>()?;
    m.add_class::<HashMapU16I32>()?;
    m.add_class::<HashMapU16I64>()?;
    m.add_class::<HashMapU16U8>()?;
    m.add_class::<HashMapU16U16>()?;
    m.add_class::<HashMapU16U32>()?;
    m.add_class::<HashMapU16U64>()?;
    m.add_class::<HashMapU16F32>()?;
    m.add_class::<HashMapU16F64>()?;

    // u32 key
    m.add_class::<HashMapU32Bool>()?;
    m.add_class::<HashMapU32I8>()?;
    m.add_class::<HashMapU32I16>()?;
    m.add_class::<HashMapU32I32>()?;
    m.add_class::<HashMapU32I64>()?;
    m.add_class::<HashMapU32U8>()?;
    m.add_class::<HashMapU32U16>()?;
    m.add_class::<HashMapU32U32>()?;
    m.add_class::<HashMapU32U64>()?;
    m.add_class::<HashMapU32F32>()?;
    m.add_class::<HashMapU32F64>()?;

    // u64 key
    m.add_class::<HashMapU64Bool>()?;
    m.add_class::<HashMapU64I8>()?;
    m.add_class::<HashMapU64I16>()?;
    m.add_class::<HashMapU64I32>()?;
    m.add_class::<HashMapU64I64>()?;
    m.add_class::<HashMapU64U8>()?;
    m.add_class::<HashMapU64U16>()?;
    m.add_class::<HashMapU64U32>()?;
    m.add_class::<HashMapU64U64>()?;
    m.add_class::<HashMapU64F32>()?;
    m.add_class::<HashMapU64F64>()?;

    // Per-segment distinct-value count kernel (CSR-grouped np.unique
    // replacement). See `segment_distinct.rs`.
    m.add_function(wrap_pyfunction!(segment_distinct_count, m)?)?;

    // Per-row identity FID/counter remap walk kernel (ALG-3/4/9). See
    // `remap_walk.rs`.
    m.add_function(wrap_pyfunction!(apply_remap_walk, m)?)?;

    // Stage-3c NUMBER-band idx_2d emission kernel (ALG-2/7/8). See
    // `number_idx_2d.rs`.
    m.add_function(wrap_pyfunction!(build_number_idx_2d_kernel, m)?)?;

    // Stage-3 per-source carrier-sign collection kernel. See
    // `carrier_signs.rs`.
    m.add_function(wrap_pyfunction!(build_carrier_signs_kernel, m)?)?;

    // Stage-3b identity carrier gather kernel (ALG-5 front matter). See
    // `identity_gather.rs`.
    m.add_function(wrap_pyfunction!(build_identity_carriers_kernel, m)?)?;

    // Stage-3a surviving inline-byte gather kernel (ALG-1). See
    // `inline_bytes.rs`.
    m.add_function(wrap_pyfunction!(build_inline_bytes_kernel, m)?)?;

    // Stage-3c NUMBER-band flat-segment column build (the per-kept-node
    // DenseColumns slice + concat feeding the number idx_2d kernel). See
    // `flat_segments.rs`.
    m.add_function(wrap_pyfunction!(build_flat_segments_kernel, m)?)?;

    // Per-node call-target-section CSR build (the vector remap path's
    // object-tree-free `_build_ct_columns` replacement: columnar ct_*
    // slices + section_of_node -> per-node CT CSR). See `node_ct_csr.rs`.
    m.add_function(wrap_pyfunction!(build_node_ct_csr_kernel, m)?)?;

    // Batched VC2 / F128 continuation-slot paint over the raw working stream
    // (the GIL-released `_promote_batched` twin: per-carrier ceil-div chunk
    // count + node-local bounds guards + segment paint, F128 NaN/Inf finite
    // filter). See `promote_batched.rs`.
    m.add_function(wrap_pyfunction!(build_promote_batched_kernel, m)?)?;

    // Batched strip + shift + prepend over the painted raw working stream
    // (the GIL-released `_strip_shift_prepend` twin: drop the <=256 band,
    // shift survivors down 256, prepend each node's self-token). See
    // `strip_shift_prepend.rs`.
    m.add_function(wrap_pyfunction!(build_strip_shift_prepend_kernel, m)?)?;

    // Single GIL-free segmented band-reduction over the per-node surviving
    // prefix, shared by the three vector-decode call sites (the preamble
    // `count_surviving_batched` / `_build_instream_columns` /
    // `build_number_chunk_columns` each recompute). See
    // `family_band_reduction.rs`.
    m.add_function(wrap_pyfunction!(build_family_band_reduction_kernel, m)?)?;

    // Fused boundary-aware InlineDecodeState field kernel (the GIL-released
    // `_state_fields.py` trio twin: runlen_number/runlen_value via per-node
    // run_lengths, the packed per-node digit cumsum, and is_negative — one
    // CSR walk over the flat raw stream). See `inline_state_fields.rs`.
    m.add_function(wrap_pyfunction!(build_inline_state_fields_kernel, m)?)?;

    // Fully-vectorized token scatter into the dense u16[B, L] token tensor
    // (the GIL-released `scatter_tokens` twin: body-start cumsum + prefix +
    // ordered prefix-then-body scatter under the straddler cut). See
    // `token_scatter.rs`.
    m.add_function(wrap_pyfunction!(build_token_scatter_kernel, m)?)?;

    // Inclusion-BFS per-level CSR frontier expansion kernel (the Rust port
    // of `LiveNodeAdjacency.expand_batch`). See `adjacency_expand.rs`.
    m.add_class::<LiveAdjacencyKernel>()?;

    // Inclusion-BFS per-level once-only / columnwise-ALL decider (the Rust
    // port of `OnceOnlyInclusion`). See `once_only_inclusion.rs`.
    m.add_class::<OnceOnlyInclusionKernel>()?;

    // Stage-3 FUSED inclusion-BFS kernel (the whole per-group + per-depth
    // loader BFS under one GIL release, reusing the Stage-1/2 cores in-Rust).
    // See `row_inclusions.rs`.
    m.add_function(wrap_pyfunction!(compute_row_inclusions_kernel, m)?)?;

    Ok(())
}
